config/routes.rb
Mechawerkz::Application.routes.draw do
  
  resources :travel_requests

  resources :bills

  resources :projects

  resources :documents

  resources :document_binders

  resources :staff_positions

  resources :staffs

  resources :contact_medium_types

  resources :contact_media

  resources :contact_companies

  resources :contact_people

  root  'static_pages#home'
  devise_for :users
  resources :users
  
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  

end

app/models/staff.rb
class Staff < ActiveRecord::Base

has_many :staff_position, foreign_key: 'staff_id'
has_many :document, :foreign_key => 'filed_by'
has_many :document, :foreign_key => 'addressed_to'
end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  # GET /staffs
  # GET /staffs.json
  def index
    @staffs = Staff.all
  end

  # GET /staffs/1
  # GET /staffs/1.json
  def show
  end

  # GET /staffs/new
  def new
    @staff = Staff.new
  end

  # GET /staffs/1/edit
  def edit
  end

  # POST /staffs
  # POST /staffs.json
  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: 'Staff was successfully created.' }
        format.json { render action: 'show', status: :created, location: @staff }
      else
        format.html { render action: 'new' }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /staffs/1
  # PATCH/PUT /staffs/1.json
  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: 'Staff was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @staff.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /staffs/1
  # DELETE /staffs/1.json
  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_staff
      @staff = Staff.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def staff_params
      params.require(:staff).permit(:id_no, :name, :kwsp_code, :tax_code, :access_id, :title_id, :file_id, :user_id, :date_of_birth, :state, :country_code, :citizenship, :birth_cert, :gravatar_email, :blood_type, :marital_status_type, :race, :religion, :gender)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_action_menu.html.erb
<td>
                <div class="btn-group dropdown">
                        <!--<button class="btn"></button>-->
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right">
                                
         <li><%= link_to content_tag(:i, "", :class => "icon-eye-open") + "   " + t('.edit', :default => t("helpers.links.edit")), edit_staff_path(staff) %></li>
                                <li><%= link_to content_tag(:i, "", :class => "icon-edit") + "   View", staff %></li>
                                <li class="divider"></li>
                                <li class="danger"><%= link_to link_to content_tag(:i, "", :class => "icon-trash") + "   " + t('.destroy', :default => t("helpers.links.destroy")),
                    staff,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }%> </li>
                        </ul>
                </div>
</td>

app/views/staffs/_form.html.erb
<%= form_for @staff, :html => {:class => 'form-horizontal' }  do |f| %>
  <% if @staff.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@staff.errors.count, "error") %> prohibited this staff from being saved:</h2>

      <ul>
      <% @staff.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :id_no, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :id_no, :class => 'form-control' %>
  </div>
   </div>

  <div class="form-group">
    <%= f.label :name, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :name, :class => 'form-control' %>
	</div>
  </div>

  <div class="form-group">
    <%= f.label :kwsp_code, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :kwsp_code, :class => 'form-control' %>
	</div>
  </div>

    <div class="form-group">
    <%= f.label :tax_code, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :tax_code, :class => 'form-control' %>
	</div>
  </div>

   <div class="form-group">
    <%= f.label :access_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :access_id, :class => 'form-control' %>
	</div>
  </div>

  <div class="form-group">
    <%= f.label :title_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :title_id, :class => 'form-control' %>
	</div>
  </div>


  <div class="form-group">
    <%= f.label :file_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :file_id, :class => 'form-control' %>
	</div>
  </div>


    <div class="form-group">
    <%= f.label :user_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :user_id, :class => 'form-control' %>
	</div>
  </div>


   <div class="form-group">
    <%= f.label :date_of_birth, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :date_of_birth, :placeholder =>"select date of birth", :id =>'date_birth', :class => 'form-control' %>
	</div>
  </div>


    <div class="form-group">
    <%= f.label :state, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-5">
    <%= f.number_field :state, :class => 'form-control' %>
	</div>
  </div>


    <div class="form-group">
    <%= f.label :country_code, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :country_code, :class => 'form-control' %>
	</div>
  </div>


   <div class="form-group">
    <%= f.label :citizenship, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :citizenship, :class => 'form-control' %>
	</div>
  </div>


    <div class="form-group">
    <%= f.label :birth_cert, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :birth_cert, :class => 'form-control' %>
	</div>
  </div>


  <div class="form-group">
    <%= f.label :gravatar_email, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :gravatar_email, :class => 'form-control' %>
	</div>
  </div>


  <div class="form-group">
    <%= f.label :blood_type, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :blood_type, :class => 'form-control' %>
	</div>
  </div>

   <div class="form-group">
    <%= f.label :marital_status_type, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :marital_status_type, :class => 'form-control' %>
	</div>
  </div>


   <div class="form-group">
    <%= f.label :race, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :race, :class => 'form-control' %>
	</div>
  </div>

  <div class="form-group">
    <%= f.label :religion, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :religion, :class => 'form-control' %>
	</div>
  </div>


  <div class="form-group">
    <%= f.label :gender, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :gender, :class => 'form-control' %>
	</div>
  </div>


  <div class="form-actions">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/staffs/edit.html.erb
<h1>Editing staff</h1>

<div class="tubbable tabs-right">
	<ul class="nav nav-tabs">
	<li><a href="#" data-toggle="tab">About</a></li>
	<li><a href="#" data-toggle="tab">Contact</a></li>
	<li><a href="#" data-toggle="tab">Employment</a></li>
	<li><a href="#" data-toggle="tab">Leave</a></li>
	<li><a href="#" data-toggle="tab">Relationship</a></li>
	<li><a href="#" data-toggle="tab">Qualification</a></li>
	<li><a href="#" data-toggle="tab">Finance</a></li>
	<ul>
</div>

<%= render 'form' %>

<%= link_to 'Show', @staff %> |
<%= link_to 'Back', staffs_path %>

app/views/staffs/index.html.erb
<h1>Listing staffs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Gravatar Icon</th>
      <th>Name</th>
        <th>IC No</th>
       <th>Date Of Birth</th>
      <th>Gender</th>
      <th>Status</th>
      
    </tr>
  </thead>

  <tbody>
    <% @staffs.each do |staff| %>
      <tr>
	 <td><%= staff.gravatar_email %></td>
	  <td><%= staff.name %></td>
        <td><%= staff.id_no %></td>
        <td><%= staff.date_of_birth %></td>
         <td><%= staff.gender %></td>

<%= render :partial => 'action_menu', :locals => { :staff => staff }%>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Staff', new_staff_path %>

app/views/staffs/new.html.erb
<h1>New staff</h1>

<%= render 'form' %>

<%= link_to 'Back', staffs_path %>

app/views/staffs/show.html.erb
<% provide(:title, 'Staff Details') %>
<%- model_class = Staff -%>
<div class="page-header">
   <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<div class="tubbable tabs-right">
	<ul class="nav nav-tabs">
	<li><a href="#" data-toggle="tab">About</a></li>
	<li><a href="#" data-toggle="tab">Contact</a></li>
	<li><a href="#" data-toggle="tab">Employment</a></li>
	<li><a href="#" data-toggle="tab">Leave</a></li>
	<li><a href="#" data-toggle="tab">Relationship</a></li>
	<li><a href="#" data-toggle="tab">Qualification</a></li>
	<li><a href="#" data-toggle="tab">Finance</a></li>
	<ul>
</div>


<p id="notice"><%= notice %></p>


<dl class="dl-horizontal">
 <dt> <strong><%= model_class.human_attribute_name(:ID_No) %>:</strong></dt>
  <dd><%= @staff.id_no %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @staff.name %></dd>


<dt>  <strong><%= model_class.human_attribute_name(:Kwsp_code) %>:</strong></dt>
  <dd><%= @staff.kwsp_code %></dd>


  <dt><strong><%= model_class.human_attribute_name(:Tax_code) %>:</strong><dt>
  <dd><%= @staff.tax_code %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:Access) %>:</strong></dt>
  <dd><%= @staff.access_id %></dd>


  <dt><strong><%= model_class.human_attribute_name(:Title) %>:</strong></dt>
  <dd><%= @staff.title_id %></dd>


<dt>  <strong><%= model_class.human_attribute_name(:File) %>:</strong></dt>
  <dd><%= @staff.file_id %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:user) %>:</strong></dt>
  <dd><%= @staff.user_id %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:Date_of_birth) %>:</strong></dt>
  <dd><%= @staff.date_of_birth %></dd>


  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @staff.state %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:country_code) %>:</strong></dt>
  <dd><%= @staff.country_code %></dd>


  <dt><strong><%= model_class.human_attribute_name(:citizenship) %>:</strong></dt>
  <dd><%= @staff.citizenship %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:birth_cert) %>:</strong></dt>
  <dd><%= @staff.birth_cert %></dd>


  <dt><strong><%= model_class.human_attribute_name(:gravatar_email) %>:</strong></dt>
  <dd><%= @staff.gravatar_email %></dd>


  <dt><strong><%= model_class.human_attribute_name(:blood_type) %>:</strong></dt>
  <dd><%= @staff.blood_type %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:marital_status_type) %>:</strong></dt>
  <dd><%= @staff.marital_status_type %></dd>


  <dt><strong><%= model_class.human_attribute_name(:race) %>:</strong></dt>
  <dd><%= @staff.race %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:religion) %>:</strong></dt>
  <dd><%= @staff.religion %></dd>


 <dt> <strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @staff.gender %></dd>
</dl>

<%= link_to 'Edit', edit_staff_path(@staff) %> |
<%= link_to 'Back', staffs_path %>