config/routes.rb
Mechawerkz::Application.routes.draw do
  
  resources :travel_requests

  resources :bills

  resources :projects

  resources :documents

  resources :document_binders

  resources :staff_positions

  resources :staffs

  resources :contact_medium_types

  resources :contact_media

  resources :contact_companies

  resources :contact_people

  root  'static_pages#home'
  devise_for :users
  resources :users
  
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	belongs_to :project, :foreign_key => 'project_id'
	belongs_to :contact_company, :foreign_key => 'pay_to'
	belongs_to :document, :foreign_key => 'document_id' 
end

app/models/contact_company.rb
class ContactCompany < ActiveRecord::Base
  has_many :contact_mediums, :foreign_key => 'company_id' 
  accepts_nested_attributes_for :contact_mediums, allow_destroy: true
  
  has_many :contact_persons
  has_many :bill, :foreign_key => 'pay_to'
end

app/models/contact_medium.rb
class ContactMedium < ActiveRecord::Base
  belongs_to :contact_company, :foreign_key => 'company_id'
  belongs_to :contact_person, :foreign_key => 'person_id' 
  belongs_to :staff
  
  belongs_to :contact_medium_type
end

app/models/contact_medium_type.rb
class ContactMediumType < ActiveRecord::Base
  has_many :contact_mediums
 
end

app/models/contact_person.rb
class ContactPerson < ActiveRecord::Base
  has_many :contact_mediums, :foreign_key => 'person_id' 
  has_many :document, :foreign_key => 'recieved_from'
  accepts_nested_attributes_for :contact_mediums, allow_destroy: true
  
  belongs_to :contact_company
end

app/models/document.rb
class Document < ActiveRecord::Base
	has_many :bill, :foreign_key => 'document_id'
	belongs_to :contact_person, :foreign_key => 'recieved_from'
	belongs_to :staff, :foreign_key => 'filed_by'
	belongs_to :staff, :foreign_key => 'addressed_to'
	
	
	end

app/models/document_binder.rb
class DocumentBinder < ActiveRecord::Base
  
  #Your code commented out ~ delete comments when done
	#has_many :staff_position,  :foreign_key => 'position.id', 'position.name'
  
  ## Read out loud : Document Binder has many staff positions.  logic?
  
	#accepts_nested_attributes_for :staff_position, allow_destroy: true
  ## this is only required with nested forms i.e add many items in one form. we only have one drop down.
  
  belongs_to :staff_position, :foreign_key => 'owned_by'
  #read out loud: DocumentBinder belongs to Staff Position. logic?
	
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :bill, :foreign_key => 'project_id'
end

app/models/role.rb
class Role < ActiveRecord::Base
  include RoleModel
end

app/models/staff.rb
class Staff < ActiveRecord::Base

has_many :staff_position, foreign_key: 'staff_id'
has_many :document, :foreign_key => 'filed_by'
has_many :document, :foreign_key => 'addressed_to'
end

app/models/staff_position.rb
class StaffPosition < ActiveRecord::Base
  has_ancestry
  
  #belong_to :document_binder,  :foreign_key => 'position.id', 'position.name'
  ## e.g Binder = Accounts, Staff Position = Accountant.
  ## read out loud : Accountant belongs to Accounts Binder. aik! orang bertuankan fail? tak logic
  ## :foreign_key => 'position.id' means database: position, field: id.  this doesnt exist.
  
  has_many :document_binders, foreign_key: 'owned_by'
  belongs_to :staff, :foreign_key => 'staff_id'
  
  #note plural, so read out loud: Staff Position has many document binders. logic?
  #now with data.  Accountant has many document binders.
  #now if singular: Account has many document binder.  grammar?
  #note there is also has_one
  #e.g  Car belongs_to owner, owner has_one car. (tho owner may have many cars but allowed only one)

  end

app/models/travel_request.rb
class TravelRequest < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  include TheRoleUserModel
         
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:project_id, :pay_to, :document_id, :category_id, :company_id, :amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.find(:all)
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
  end  
  

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Mechawerkz App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
  


end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  #def devise_error_messages!
  #  return "" if resource.errors.empty?
  #
  #  messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
  #  sentence = I18n.t("errors.messages.not_saved",
  #                    :count => resource.errors.count,
  #                    :resource => resource.class.model_name.human.downcase)
  #
  #  html = <<-HTML
  #  <div id="error_explanation">
  #    <div id="alert alert-danger">#{sentence}</div>
  #    <ul>#{messages}</ul>
  #  </div>
  #  HTML
  #
  #  html.html_safe
  #end
  
  def devise_error_messages!
    'KABOOM!'
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/bills/_form.html.erb
<%= form_for @bill, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.collection_select :project_id, Project.find(:all), :id, :name, :include_blank=> 'Select Project', :class => 'form-control'  %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :pay_to, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.collection_select :pay_to, ContactCompany.find(:all), :id, :name, :include_blank=> 'Select Pay to', :class => 'form-control'  %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :document_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.collection_select :document_id, Document.find(:all), :id, :title, :include_blank=> 'Select document', :class => 'form-control'  %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :category_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :category_id, :class =>'form-control' %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :company_id, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.number_field :company_id, :class =>'form-control' %>
  </div>
  </div>

  <div class="form-group">
    <%= f.label :amount, :class => 'col-lg-2 control-label' %>
	<div class="col-lg-6">
    <%= f.text_field :amount, :class =>'form-control' %>
  </div>
  </div>


 <div class="form-actions">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing of Bills</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Project</th>
      <th>Pay to</th>
      <th>Document</th>
      <th>Category</th>
      <th>Company</th>
      <th>Amount</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.project_id %></td>
        <td><%= bill.pay_to %></td>
        <td><%= bill.document_id %></td>
        <td><%= bill.category_id %></td>
        <td><%= bill.company_id %></td>
        <td><%= bill.amount %></td>
        <td><button type="button" class="btn btn-success btn-sm"><%= link_to 'Show', bill %></td>
        <td><button type="button" class="btn btn-primary btn-sm"><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><button type="button" class="btn btn-danger btn-sm"><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<% provide(:title, 'Bill Details') %>
<%- model_class = Bill -%>
<div class="page-header">
   <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:project) %>:</strong></dt>
  <dd><%= @bill.project_id %></dd>


  <dt><strong><%= model_class.human_attribute_name(:pay_to) %>:</strong></dt>
  <dd><%= @bill.pay_to %></dd>


  <dt><strong><%= model_class.human_attribute_name(:document) %>:</strong></dt>
  <dd><%= @bill.document_id %></dd>


  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @bill.category_id %></dd>


  <dt><strong><%= model_class.human_attribute_name(:company) %>:</strong></dt>
  <dd><%= @bill.company_id %></dd>


  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @bill.amount %></dd>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>