config/routes.rb
Mechawerkz::Application.routes.draw do
  
  resources :travel_requests

  resources :bills

  resources :projects

  resources :documents

  resources :document_binders

  resources :staff_positions

  resources :staffs

  resources :contact_medium_types

  resources :contact_media

  resources :contact_companies

  resources :contact_people

  root  'static_pages#home'
  devise_for :users
  resources :users
  
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  

end

app/models/document.rb
class Document < ActiveRecord::Base
	has_many :bill, :foreign_key => 'document_id'
	belongs_to :contact_person, :foreign_key => 'recieved_from'
	belongs_to :staff, :foreign_key => 'filed_by'
	belongs_to :staff, :foreign_key => 'addressed_to'
	
	
	end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:ref_no, :title, :project_id, :document_category_id, :type, :document_date, :recieved_from, :received_on, :filed_by, :addressed_to, :description, :binder_id, :document_file_name, :document_content_type, :document_file_size, :document_updated_at)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_action_menu.html.erb
<td>
                <div class="btn-group dropdown">
                        <!--<button class="btn"></button>-->
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right">
                                
         <li><%= link_to content_tag(:i, "", :class => "icon-eye-open") + "   " + t('.edit', :default => t("helpers.links.edit")), edit_document_path(document) %></li>
                                <li><%= link_to content_tag(:i, "", :class => "icon-edit") + "   View", document %></li>
                                <li class="divider"></li>
                                <li class="danger"><%= link_to link_to content_tag(:i, "", :class => "icon-trash") + "   " + t('.destroy', :default => t("helpers.links.destroy")),
                    document,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }%> </li>
                        </ul>
                </div>
</td>

app/views/documents/_form.html.erb
<%= form_for @document, :html => { :class => 'form-horizontal'} do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :ref_no, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :ref_no, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :project_id, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.number_field :project_id, :class => 'form-control' %>
    </div>
  </div>

    <div class="form-group">
    <%= f.label :document_category_id, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.number_field :document_category_id, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :type, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :type, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :document_date, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :document_date, :placeholder =>"select document date", :id => "document_date", :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :recieved_from, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.collection_select :recieved_from, ContactPerson.find(:all), :id, :name, :include_blank=> 'Select Person', :class => 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :received_on, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :received_on, :placeholder =>"select receive on date", :id =>"received_on", :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :filed_by, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
            <%= f.collection_select :filed_by, Staff.find(:all), :id, :name, :include_blank=> 'Select Staff', :class => 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :addressed_to, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.collection_select :filed_by, Staff.find(:all), :id, :name, :include_blank=> 'Select Staff', :class => 'form-control'  %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :binder_id, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.number_field :binder_id, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :document_file_name, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :document_file_name, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :document_content_type, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      
	Incoming <%= f.radio_button :document_content_type, "incoming" , :class => 'form-control'  %> 
	Outgoing <%= f.radio_button :document_content_type, "outgoing" , :class => 'form-control'  %> 
    </div>
  </div>

  <div class="form-group">
    <%= f.label :document_file_size, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.number_field :document_file_size, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :document_updated_at, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :document_updated_at, :placeholder =>"select date and time update", :id => "date_time", :class => 'form-control' %>
    </div>
  </div>


 <div class="form-actions">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing Documents</h1>

<table class="table table-striped">
  <thead>
    <tr>
      
      <th>Title</th>
    
      <th>Recieved from</th>

      <th>Filed by</th>
      <th>Status</th>
      
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        
        <td><%= document.title %></td>

        <td><%= document.recieved_from %></td>
      
        <td><%= document.filed_by %></td>
	<%= render :partial => 'action_menu', :locals => { :document => document }%>
       
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<% provide(:title, 'Document Details') %>
<%- model_class = Document -%>
<div class="page-header">
   <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">

  <dt><strong><%= model_class.human_attribute_name(:ref_no) %>:</strong></dt>
  <dd><%= @document.ref_no %></dd>



  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @document.title %></dd>



  <dt><strong><%= model_class.human_attribute_name(:project) %>:</strong></dt>
  <dd><%= @document.project_id %></dd>



  <dt><strong><%= model_class.human_attribute_name(:document_category) %>:</strong></dt>
 <dd> <%= @document.document_category_id %></dd>



  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @document.type %></dd>



  <dt><strong><%= model_class.human_attribute_name(:document_date) %>:</strong></dt>
  <dd><%= @document.document_date %></dd>



  <dt><strong><%= model_class.human_attribute_name(:recieved_from) %>:</strong></dt>
  <dd><%= @document.recieved_from %></dd>



  <dt><strong><%= model_class.human_attribute_name(:received_on) %>:</strong></dt>
  <dd><%= @document.received_on %></dd>



  <dt><strong><%= model_class.human_attribute_name(:filed_by) %>:</strong></dt>
  <dd><%= @document.filed_by %></dd>



  <dt><strong><%= model_class.human_attribute_name(:addressed_to) %>:</strong></dt>
  <dd><%= @document.addressed_to %></dd>



  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @document.description %></dd>



  <dt><strong><%= model_class.human_attribute_name(:binder) %>:</strong></dt>
  <dd><%= @document.binder_id %></dd>



  <dt><strong><%= model_class.human_attribute_name(:document_file_name) %>:</strong></dt>
  <dd><%= @document.document_file_name %></dd>



  <dt><strong><%= model_class.human_attribute_name(:document_content_type) %>:</strong></dt>
  <dd><%= @document.document_content_type %></dd>



  <dt><strong><%= model_class.human_attribute_name(:document_file_size) %>:</strong></dt>
  <dd><%= @document.document_file_size %></dd>



  <dt><strong><%= model_class.human_attribute_name(:document_updated_at) %>:</strong></dt>
  <dd><%= @document.document_updated_at %></dd>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>