config/routes.rb
Mechawerkz::Application.routes.draw do
  
  resources :travel_requests

  resources :bills

  resources :projects

  resources :documents

  resources :document_binders

  resources :staff_positions

  resources :staffs

  resources :contact_medium_types

  resources :contact_media

  resources :contact_companies

  resources :contact_people

  root  'static_pages#home'
  devise_for :users
  resources :users
  
  
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

  

end

app/models/document_binder.rb
class DocumentBinder < ActiveRecord::Base
  
  #Your code commented out ~ delete comments when done
	#has_many :staff_position,  :foreign_key => 'position.id', 'position.name'
  
  ## Read out loud : Document Binder has many staff positions.  logic?
  
	#accepts_nested_attributes_for :staff_position, allow_destroy: true
  ## this is only required with nested forms i.e add many items in one form. we only have one drop down.
  
  belongs_to :staff_position, :foreign_key => 'owned_by'
  #read out loud: DocumentBinder belongs to Staff Position. logic?
	
end

app/controllers/document_binders_controller.rb
class DocumentBindersController < ApplicationController
  before_action :set_document_binder, only: [:show, :edit, :update, :destroy]

  # GET /document_binders
  # GET /document_binders.json
  def index
    @document_binders = DocumentBinder.all
  end

  # GET /document_binders/1
  # GET /document_binders/1.json
  def show
  end

  # GET /document_binders/new
  def new
    @document_binder = DocumentBinder.new
  end

  # GET /document_binders/1/edit
  def edit
  end

  # POST /document_binders
  # POST /document_binders.json
  def create
    @document_binder = DocumentBinder.new(document_binder_params)

    respond_to do |format|
      if @document_binder.save
        format.html { redirect_to @document_binder, notice: 'Document binder was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document_binder }
      else
        format.html { render action: 'new' }
        format.json { render json: @document_binder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /document_binders/1
  # PATCH/PUT /document_binders/1.json
  def update
    respond_to do |format|
      if @document_binder.update(document_binder_params)
        format.html { redirect_to @document_binder, notice: 'Document binder was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document_binder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /document_binders/1
  # DELETE /document_binders/1.json
  def destroy
    @document_binder.destroy
    respond_to do |format|
      format.html { redirect_to document_binders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document_binder
      @document_binder = DocumentBinder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_binder_params
      params.require(:document_binder).permit(:code, :description, :volume, :contact_company_id, :owned_by, :location_id)
    end
end

app/helpers/document_binders_helper.rb
module DocumentBindersHelper
end

app/views/document_binders/_action_menu.html.erb
<td>
                <div class="btn-group dropdown">
                        <!--<button class="btn"></button>-->
                        <button class="btn dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu pull-right">
                                
         <li><%= link_to content_tag(:i, "", :class => "icon-eye-open") + "   " + t('.edit', :default => t("helpers.links.edit")), edit_document_binder_path(document_binder) %></li>
                                <li><%= link_to content_tag(:i, "", :class => "icon-edit") + "   View", document_binder %></li>
                                <li class="divider"></li>
                                <li class="danger"><%= link_to link_to content_tag(:i, "", :class => "icon-trash") + "   " + t('.destroy', :default => t("helpers.links.destroy")),
                    document_binder,
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }%> </li>
                        </ul>
                </div>
</td>

app/views/document_binders/_form.html.erb
<%= form_for @document_binder, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @document_binder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document_binder.errors.count, "error") %> prohibited this document_binder from being saved:</h2>

      <ul>
      <% @document_binder.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :code, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :code, :class => 'form-control' %>
    </div>
  </div>

 <div class="form-group">
    <%= f.label :description, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :volume, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
    <%= f.select :volume, 1..10, :class =>'form-control'  %>
    </div>
  </div>

 <div class="form-group">
    <%= f.label :contact_company_id, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.number_field :contact_company_id, :class => 'form-control' %>
    </div>
  </div>

 <div class="form-group">
    <%= f.label :owned_by, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.collection_select :owned_by, StaffPosition.find(:all), :id, :name, :include_blank=> 'Select owner', :class => 'form-control'  %>
    </div>
  </div>

   <div class="form-group">
    <%= f.label :location_id, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-6">
      <%= f.number_field :location_id, :class => 'form-control' %>
    </div>
  </div>

   <div class="form-actions">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => "btn btn-primary" %>
    </div>

<% end %>

app/views/document_binders/edit.html.erb
<h1>Editing Document Binder</h1>

<%= render 'form' %>

<%= link_to 'Show', @document_binder %> |
<%= link_to 'Back', document_binders_path %>

app/views/document_binders/index.html.erb
<h1>Listing Document Binders</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Volume</th>
      <th>Contact company</th>
      <th>Owned by</th>
      <th>Location</th>
      <th>Status</th>
      
    </tr>
  </thead>

  <tbody>
    <% @document_binders.each do |document_binder| %>
      <tr>
        <td><%= document_binder.code %></td>
        <td><%= document_binder.description %></td>
        <td><%= document_binder.volume %></td>
        <td><%= document_binder.contact_company_id %></td>
        <td><%= document_binder.owned_by %></td>
        <td><%= document_binder.location_id %></td>
<%= render :partial => 'action_menu', :locals => { :document_binder => document_binder }%> 
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document binder', new_document_binder_path %>

app/views/document_binders/new.html.erb
<h1>New Document Binder</h1>

<%= render 'form' %>

<%= link_to 'Back', document_binders_path %>

app/views/document_binders/show.html.erb
<% provide(:title, 'Document Binder Details') %>
<%- model_class = DocumentBinder -%>
<div class="page-header">
   <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @document_binder.code %></dd>



  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @document_binder.description %></dd>



  <dt><strong><%= model_class.human_attribute_name(:volume) %>:</strong></dt>
  <dd><%= @document_binder.volume %></dd>



  <dt><strong><%= model_class.human_attribute_name(:contact_company) %>:</strong></dt>
  <dd><%= @document_binder.contact_company_id %></dd>



  <dt><strong><%= model_class.human_attribute_name(:owned_by) %>:</strong></dt>
  <dd><%= @document_binder.owned_by %><dd>



  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @document_binder.location_id %></dd>
</dl>


<%= link_to 'Edit', edit_document_binder_path(@document_binder) %> |
<%= link_to 'Back', document_binders_path %>